services:
  npm:
    profiles: ["proxy"]
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt
    networks:
      - spring_mysql_api

  mysql_db:
    image: mysql:8.0
    container_name: deploy-db
    env_file:
      - .env
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:

      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TZ}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u${MYSQL_USER} -p${MYSQL_PASSWORD} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - spring_mysql_api

  spring_app:
    image: ${ECR_REGISTRY}fa-project:latest
    container_name: spring_app
    env_file:
      - .env
    volumes:
      # [EC2 서버의 프롬프트 폴더 절대경로] : [컨테이너 내부 경로]
      - /home/ubuntu/2026_TRIPLES_TEAM_2_BE/src/main/resources/prompts:/app/prompts
    environment:
      PROMPT_ADVICE_SYSTEM: file:/app/prompts/advice/generateAdviceSystem.st
      PROMPT_ADVICE_USER: file:/app/prompts/advice/generateAdvice.st
      PROMPT_AIREPORT_SYSTEM: file:/app/prompts/aiReport/generateAiReportSystem.st
      PROMPT_AIREPORT_USER: file:/app/prompts/aiReport/generateAiReport.st
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: ${DB_JDBC_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      mysql_db:
        condition: service_healthy
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - spring_mysql_api

  redis:
    image: redis:6.2-alpine
    container_name: deploy-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - spring_mysql_api



networks:
  spring_mysql_api:
    driver: bridge

volumes:
  redis-data:
  mysql-data:
